print(5+2)# SUMA
print(5-2)# RESTAS
print(5*2)# MULTIPLICAICON
print(5/2)# DIVISION
print(5//2)# DIVISION ENTERA O SIN DECIMAL
print(5%2)# MODULO (RESTO DE LA DIVISION ANTES DEL PUNTO DECIMAL)
print(5**2)# POTENCIA